--[[    id值为 EVENT_模块名_具体事件名]]
--
XEventId = {
    --社交
    EVENT_CHAT_RECEIVE_PRIVATECHAT = "EVENT_CHAT_RECEIVE_PRIVATECHAT", --收到私聊
    EVENT_CHAT_RECEIVE_WORLD_MSG = "EVENT_CHAT_RECEIVE_WORLD_MSG", --收到世界聊天信息
    EVENT_CHAT_RECEIVE_ROOM_MSG = "EVENT_CHAT_RECEIVE_ROOM_MSG", --收到房间聊天信息
    EVENT_CHAT_MSG_SYNC = "EVENT_CHAT_MSG_SYNC", --同步私聊
    EVENT_CHAT_OPEN = "EVENT_CHAT_OPEN", --打开聊天界面
    EVENT_CHAT_CLOSE = "EVENT_CHAT_CLOSE", --关闭聊天界面
    EVENT_CHAT_CHANNEL_CHANGED = "EVENT_CHAT_CHANNEL_CHANGED", --聊天频道id更换
    EVENT_CHAT_SERVER_CHANNEL_CHANGED = "EVENT_CHAT_SERVER_CHANNEL_CHANGED", --服务端主动更换聊天频道

    EVENT_FRIEND_DELETE = "EVENT_FRIEND_DELETE", --删除好友
    EVENT_FRIEND_WAITING_PASS = "EVENT_FRIEND_WAITING_PASS", --等待通过，新的好友申请
    EVENT_FRIEND_OPEN_PRIVATE_VIEW = "EVENT_FRIEND_OPEN_PRIVATE_VIEW", --打开私聊界面
    EVENT_FRIEND_READ_PRIVATE_MSG = "EVENT_FRIEND_READ_PRIVATE_MSG", --读取私聊信息

    EVENT_PULL_SCROLLVIEW_END = "EVENT_PULL_SCROLLVIEW_END", --数据拉到底了    --后续会清掉
    EVENT_PULL_SCROLLVIEW_UP = "EVENT_PULL_SCROLLVIEW_UP", --数据拉到头了    --后续会清掉

    --邮件事件
    EVENT_MAIL_SYNC = "EVENT_MAIL_SYNC", --服务端同步邮件,
    EVENT_MAIL_READ = "EVENT_MAIL_READ", --读取邮件,
    EVENT_MAIL_DELETE = "EVENT_MAIL_DELETE", --删除邮件,
    EVENT_MAIL_GET_MAIL_REWARD = 'EVENT_MAIL_GET_MAIL_REWARD', --领取邮件附件
    EVENT_MAIL_GET_ALL_MAIL_REWARD = 'EVENT_MAIL_GET_ALL_MAIL_REWARD', --一键领取附件
    EVENT_MAIL_COUNT_CHEAK = 'EVENT_MAIL_COUNT_CHEAK',--邮件数发生改变
    --角色事件
    EVENT_CHARACTER_ADD_SYNC = "EVENT_CHARACTER_ADD_SYNC", --添加构造体
    EVENT_CHARACTER_LEVEL_UP = "EVENT_CHARACTER_LEVEL_UP", --升级
    EVENT_CHARACTER_QUALITY_STAR_PROMOTE = "EVENT_CHARACTER_QUALITY_STAR_PROMOTE", --进化
    EVENT_CHARACTER_QUALITY_PROMOTE = "EVENT_CHARACTER_QUALITY_PROMOTE", --升品
    EVENT_CHARACTER_GRADE = "EVENT_CHARACTER_GRADE", --晋升，升星
    EVENT_CHARACTER_GRADE_PART = "EVENT_CHARACTER_GRADE_PART", --小晋升
    EVENT_CHARACTER_SKILL_UNLOCK = "EVENT_CHARACTER_SKILL_UNLOCK", --解锁技能
    EVENT_CHARACTER_SKILL_UP = "EVENT_CHARACTER_SKILL_UP", --升级技能
    EVENT_CHARACTER_INCREASE_TIP = "EVENT_CHARACTER_INCREASE_TIP", -- 角色属性提升后提醒
    EVENT_CHARACTER_FIRST_GET = "EVENT_CHARACTER_FIRST_GET", --首次获得角色
    EVENT_CHARACTER_SYN = "EVENT_CHARACTER_SYN", --角色信息变更

    --联机Boss事件
    EVENT_ONLINEBOSS_UPDATE = "EVENT_ONLINEBOSS_UPDATE",        --数据刷新
    EVENT_ONLINEBOSS_REFRESH = "EVENT_ONLINEBOSS_REFRESH",      --活动刷新
    EVENT_ONLINEBOSS_DROPREWARD_NOTIFY = "EVENT_ONLINEBOSS_DROPREWARD_NOTIFY", --抽奖通知

    --房间事件
    EVENT_ROOM_REFRESH = "EVENT_ROOM_REFRESH", --房间刷新
    EVENT_ROOM_PLAYER_ENTER = "EVENT_ROOM_PLAYER_ENTER", --玩家加入
    EVENT_ROOM_PLAYER_LEAVE = "EVENT_ROOM_PLAYER_LEAVE", --玩家离开
    EVENT_ROOM_PLAYER_STAGE_REFRESH = "EVENT_ROOM_PLAYER_STAGE_REFRESH", --玩家状态更新
    EVENT_ROOM_PLAYER_NPC_REFRESH = "EVENT_ROOM_PLAYER_NPC_REFRESH", --玩家角色信息更新
    EVENT_ROOM_AUTO_MATCH_CHANGE = "EVENT_ROOM_AUTO_MATCH_CHANGE", --房间自动匹配状态修改
    EVENT_ROOM_STAGE_LEVEL_CHANGE = "EVENT_ROOM_STAGE_LEVEL_CHANGE", --房间难度等级修改
    EVENT_ROOM_STAGE_ABILITY_LIMIT_CHANGE = "EVENT_ROOM_STAGE_ABILITY_LIMIT_CHANGE", --房间战力修改
    EVENT_ROOM_STAGE_CHANGE = "EVENT_ROOM_STAGE_CHANGE", --房间状态修改

    EVENT_ROOM_MATCH = "EVENT_ROOM_MATCH", --匹配
    EVENT_ROOM_CANCEL_MATCH = "EVENT_ROOM_CANCEL_MATCH", --取消匹配
    EVENT_ROOM_ENTER_ROOM = "EVENT_ROOM_ENTER_ROOM", --进入房间
    EVENT_ROOM_KICKOUT = "EVENT_ROOM_KICKOUT", --踢出房间
    EVENT_ROOM_LEAVE_ROOM = "EVENT_ROOM_LEAVE_ROOM", --离开房间(主动退出或被踢出房间)
    EVENT_ROOM_COUNT_DOWN = "EVENT_ROOM_COUNT_DOWN", --倒计时

    --UI
    UiOpenPanel = "EVENT_UI_OPEN_PANEL", --参数：（bool, string）,打开/关闭，ui名称
    EVENT_MAINUI_ENABLE = "EVENT_MAINUI_ENABLE", --主界面显示

    --引导
    EVENT_GUIDE_REQ_OPEN_SUCCESS = "EVENT_GUIDE_REQ_OPEN_SUCCESS", --请求引导完成
    EVENT_GUIDE_START = "EVENT_GUIDE_START", --引导开始
    EVENT_GUIDE_END = "EVENT_GUIDE_END", --引导结束
    EVENT_GUIDE_COMPLETED_SUCCESS = "EVENT_GUIDE_COMPLETED_SUCCESS", --请求引导完成


    EVENT_GUIDE_STEP_OPEN_EVENT = "EVENT_GUIDE_STEP_OPEN_EVENT", --检测步骤

    --功能开启
    EVENT_FUNCTION_OPEN_COMPLETE = "EVENT_FUNCTION_OPEN_COMPLETE", --功能开启

    EVENT_FUNCTION_EVENT_START = "EVENT_FUNCTION_EVENT_START", --功能开始
    EVENT_FUNCTION_EVENT_COMPLETE = "EVENT_FUNCTION_EVENT_COMPLETE", --功能开启完成
    EVENT_FUNCTION_EVENT_END = "EVENT_FUNCTION_EVENT_END", --功能结束

    --紧急事件
    EVENT_URGENTEVENT_SYNC = "EVENT_URGENTEVENT_SYNC", -- 收到紧急事件

    --副本
    EVENT_FUBEN_DAILY_REFRESH = "EVENT_FUBEN_DAILY_REFRESH", --日常副本刷新
    EVENT_FUBEN_REFRESH_STAGE_DATA = "EVENT_FUBEN_REFRESH_STAGE_DATA", --副本变更推送
    EVENT_FUBEN_CHAPTER_REWARD = "EVENT_FUBEN_CHAPTER_REWARD", --领取章节奖励
    EVENT_FUBEN_CLOSE_FUBENSTAGEDETAIL = "EVENT_FUBEN_CLOSE_FUBENSTAGEDETAIL", --关闭副本详细界面
    EVENT_FUBEN_ENTERFIGHT = "EVENT_FUBEN_ENTERFIGHT", --点击作战开始
    EVENT_FUBEN_STAGE_SYNC = "EVENT_FUBEN_STAGE_SYNC", --stage同步
    EVENT_FUBEN_NEW_STAGE = "EVENT_FUBEN_NEW_STAGE", --新的关卡
    EVENT_FUBEN_NEW_MAIN_LINE_CHAPTER = "EVENT_FUBEN_NEW_MAIN_LINE_CHAPTER", --新的主线章节
    EVENT_FUBEN_SETTLE_REWARD = "EVENT_FUBEN_SETTLE_REWARD", --副本结算奖励
    EVENT_FUBEN_SHOW_REWARD = "EVENT_FUBEN_SHOW_REWARD", --显示副本奖励
    EVENT_FUBEN_SINGLE_BOSS_SYNC = "EVENT_FUBEN_SINGLE_BOSS_SYNC", --单机boss数据刷新
    EVENT_FUBEN_CHANGE_MAIN_LINE_DIFFICULT = "EVENT_FUBEN_CHANGE_MAIN_LINE_DIFFICULT", --修改主线副本难度
    EVENT_ENTER_FIGHT = "EVENT_ENTER_FIGHT", --进入战斗
    EVENT_FUBEN_EXPLORE_UPDATE = "EVENT_FUBEN_EXPLORE_UPDATE", --探索更新UI
    EVENT_FUBEN_EXPLORE_UPDATEBUFF = "EVENT_FUBEN_EXPLORE_UPDATEBUFF", --更新探索buff UI
    EVENT_FUBEN_RESOURCE_AUTOSELECT = "EVENT_FUBEN_RESOURCE_AUTOSELECT",--资源自动选中
    EVENT_FUBEN_PREQUEL_AUTOSELECT = "EVENT_FUBEN_PREQUEL_AUTOSELECT",--前传自动选中 
    EVENT_FUBEN_MAINLINE_TAB_SELECT = "EVENT_FUBEN_MAINLINE_TAB_SELECT",--剧情界面子标签页自动选中
    EVENT_FUBEN_MAINLINE_DIFFICUTY_SELECT = "EVENT_FUBEN_MAINLINE_DIFFICUTY_SELECT",--主线难度标签页自动选中
    EVENT_FUBEN_SETTLE_FAIL = "EVENT_FUBEN_FIGHT_CHECK_FAIL",--副本结算失败

    --活动相关
    EVENT_ACTIVITY_MAINLINE_STATE_CHANGE = "EVENT_ACTIVITY_MAINLINE_STATE_CHANGE", --主线副本抢先体验活动状态变更

    --自动作战
    EVENT_AUTO_FIGHT_CHANGE = "EVENT_AUTO_FIGHT_CHANGE", --自动作战状态改变
    EVENT_AUTO_FIGHT_START = "EVENT_AUTO_FIGHT_START", --自动作战开始
    EVENT_AUTO_FIGHT_COMPLETE = "EVENT_AUTO_FIGHT_COMPLETE", --自动作战完成
    EVENT_AUTO_FIGHT_REMOVE = "EVENT_AUTO_FIGHT_REMOVE", --自动作战移除

    --竞技
    EVENT_ARENA_TEAM_CHANGE = "EVENT_ARENA_TEAM_CHANGE", --竞技队伍变化
    EVENT_ARENA_TEAM_INITIATIVE_LEAVE = "EVENT_ARENA_TEAM_INITIATIVE_LEAVE", --竞技主动离队
    EVENT_ARENA_TEAM_RECEIVE_APPLY_DATA = "EVENT_ARENA_TEAM_RECEIVE_APPLY_DATA", --竞技得到申请列表
    EVENT_ARENA_TEAM_APPLY_CHANGE = "EVENT_ARENA_TEAM_APPLY_CHANGE", --竞技申请列表变化
    EVENT_ARENA_TEAM_NEW_APPLY_ENTER = "EVENT_ARENA_TEAM_NEW_APPLY_ENTER", --竞技新申请信息数量变化
    EVENT_ARENA_MAIN_INFO = "EVENT_ARENA_MAIN_INFO", --竞技主界面信息
    EVENT_ARENA_REFRESH_TEAM_RANK_INFO = "EVENT_ARENA_REFRESH_TEAM_RANK_INFO", --竞技刷新排行信息
    EVENT_ARENA_REFRESH_AREA_INFO = "EVENT_ARENA_REFRESH_AREA_INFO", --竞技刷新战区信息
    EVENT_ARENA_UNLOCK_AREA = "EVENT_ARENA_UNLOCK_AREA", --竞技解锁战区
    EVENT_ARENA_RESULT_CLOSE = "EVENT_ARENA_RESULT_CLOSE", --竞技关闭奖励界面

    --任务
    EVENT_TASK_SYNC = "EVENT_TASK_SYNC", --任务改变
    EVENT_FINISH_TASK = "EVENT_FINISH_TASK", --任务改变
    EVENT_TASK_COURSE_REWAED = "EVENT_TASK_COURSE_REWAED", --领取历程奖励
    EVENT_TASK_TAB_CHANGE = "EVENT_TASK_TAB_CHANGE",        --任务tab改变
    EVENT_TASK_FINISH_FAIL = "EVENT_TASK_FINISH_FAIL",      --任务领取失败

    --道具
    EVENT_ITEM_COUNT_UPDATE_PREFIX = "EVENT_ITEM_COUNT_UPDATE_",
    EVENT_ITEM_BUYTIEMS_UPDATE_PREFIX = "EVENT_ITEM_BUYTIMES_UPDATE_",
    EVENT_ITEM_BUYASSET = "EVENT_ITEM_BUYASSET", -- 购买道具
    EVENT_ITEM_USE = "EVENT_ITEM_USE", -- 使用道具
    EVENT_TIMELIMIT_ITEM_USE = "EVENT_TIMELIMIT_ITEM_USE", -- 使用限时道具
    EVENT_ITEM_RECYCLE = "EVENT_ITEM_RECYCLE", -- 回收道具

    --玩家
    EVENT_USERID_CHANGE = "EVENT_USERID_CHANGE", -- 更换账号
    EVENT_USERNAME_CHANGE = "EVENT_USERNAME_CHANGE", -- 更换账号
    EVENT_USER_LOGOUT = "EVENT_USER_LOGOUT", -- 登出
    EVENT_LOGIN_SUCCESS = "EVENT_LOGIN_SUCCESS", -- 登陆成功
    EVENT_LOGIN_DATA_LOAD_COMPLETE = "EVENT_LOGIN_DATA_LOAD_COMPLETE", -- 登录数据加载完毕
    EVENT_NETWORK_DISCONNECT = "EVENT_NETWORK_DISCONNECT", -- 断开连接

    EVENT_NEW_PLAYER = "EVENT_NEW_PLAYER", -- 新创建的玩家
    EVENT_PLAYER_SET_NAME = "EVENT_PLAYER_SET_NAME", -- 玩家改名
    EVENT_PLAYER_LEVEL_CHANGE = "EVENT_PLAYER_LEVEL_CHANGE", -- 等级发生变化

    EVENT_PLAYER_LEVEL_UP_ANIMATION_END = "EVENT_PLAYER_LEVEL_UP_ANIMATION_END", --玩家等级提升动画结束

    --赏金任务
    EVENT_BOUNTYTASK_INFO_CHANGE_NOTIFY = "EVENT_BOUNTYTASK_INFO_CHANGE_NOTIFY", --赏金任务改变推送
    EVENT_BOUNTYTASK_ACCEPT_TASK = "EVENT_BOUNTYTASK_ACCEPT_TASK", --接受赏金任务
    EVENT_BOUNTYTASK_ACCEPT_TASK_REWARD = "EVENT_BOUNTYTASK_ACCEPT_TASK_REWARD", --接受赏金任务
    EVENT_BOUNTYTASK_TASK_COMPLETE_NOTIFY = "EVENT_BOUNTYTASK_TASK_COMPLETE_NOTIFY", --任务完成
    EVENT_BOUNTYTASK_TASK_REFRESH = "EVENT_BOUNTYTASK_TASK_REFRESH", --任务池刷新

    --派遣
    EVENT_TASKFORCE_INFO_NOTIFY = "EVENT_TASKFORCE_INFO_NOTIFY", --派遣推送
    EVENT_TASKFORCE_SECTIONCHANGE_NOTIFY = "EVENT_TASKFORCE_SECTIONCHANGE_NOTIFY", --派遣章节改变推送
    EVENT_TASKFORCE_MAXTASKFORCECOUNT_CHANGE_NOTIFY = "EVENT_TASKFORCE_MAXTASKFORCECOUNT_CHANGE_NOTIFY", --可派遣队伍最大数量改变推送
    EVENT_TASKFORCE_COMPLETE_NOTIFY = "EVENT_TASKFORCE_COMPLETE_NOTIFY", --派遣任务完成推送
    EVENT_TASKFORCE_GIVEUP_TASK_REQUEST = "EVENT_TASKFORCE_GIVEUP_TASK_REQUEST", --派遣放弃任务
    EVENT_TASKFORCE_ACCEPT_TASK_REQUEST = "EVENT_TASKFORCE_ACCEPT_TASK_REQUEST", --派遣接受任务
    EVENT_TASKFORCE_REFRESH_REQUEST = "EVENT_TASKFORCE_REFRESH_REQUEST", --派遣刷新任务池
    EVENT_TASKFORCE_TASKFINISH_REQUEST = "EVENT_TASKFORCE_TASKFINISH_REQUEST", --派遣立即完成任务
    EVENT_TASKFORCE_ACCEPT_REWARD_REQUEST = "EVENT_TASKFORCE_ACCEPT_REWARD_REQUEST", --派遣获得奖励
    EVENT_TASKFORCE_TIP_MISSION_END = "EVENT_TASKFORCE_TIP_MISSION_END", --派遣队伍开启动画结束

    --战斗
    EVENT_FIGHT_BEGIN_PLAYMOVIE = "EVENT_FIGHT_BEGIN_PLAYMOVIE", --战斗开始前播放剧情
    EVENT_FIGHT_LOADINGFINISHED = "EVENT_FIGHT_LOADINGFINISHED", --战斗Loading已打开
    EVENT_FIGHT_PROGRESS = "EVENT_FIGHT_PROGRESS", --战斗loading进度
    EVENT_FIGHT_RESULT = "EVENT_FIGHT_RESULT", --战斗结果
    EVENT_FIGHT_RESULT_WIN = "EVENT_FIGHT_RESULT_WIN", --战斗结果

    --投票
    EVENT_VOTE_REFRESH = "EVENT_VOTE_REFRESH", --投票数据更新

    --装备
    EVENT_EQUIP_PUTON_NOTYFY = "EVENT_EQUIP_PUTON_NOTYFY", --穿上
    EVENT_EQUIP_PUTON_WEAPON_NOTYFY = "EVENT_EQUIP_PUTON_WEAPON_NOTYFY", --穿上武器
    EVENT_EQUIP_TAKEOFF_NOTYFY = "EVENT_EQUIP_TAKEOFF_NOTYFY", --脱下单个
    EVENT_EQUIPLIST_TAKEOFF_NOTYFY = "EVENT_EQUIPLIST_TAKEOFF_NOTYFY", --脱下装备列表
    EVENT_EQUIP_LOCK_STATUS_CHANGE_NOTYFY = "EVENT_EQUIP_LOCK_STATUS_CHANGE_NOTYFY", --锁定状态变更
    EVENT_EQUIP_STRENGTHEN_NOTYFY = "EVENT_EQUIP_STRENGTHEN_NOTYFY", --强化
    EVENT_EQUIP_BREAKTHROUGH_NOTYFY = "EVENT_EQUIP_BREAKTHROUGH_NOTYFY", --突破
    EVENT_EQUIP_RESONANCE_NOTYFY = "EVENT_EQUIP_RESONANCE_NOTYFY", --共鸣随机技能返回
    EVENT_EQUIP_RESONANCE_ACK_NOTYFY = "EVENT_EQUIP_RESONANCE_ACK_NOTYFY", --共鸣确认选择技能
    EVENT_EQUIP_DATA_CHANGE_NOTIFY = "EVENT_EQUIP_DATA_CHANGE_NOTYFY", --装备数据变更
    EVENT_EQUIP_DATA_INIT_NOTIFY = "EVENT_EQUIP_DATA_INIT_NOTYFY", --装备数据初始化完成
    EVENT_EQUIP_CAN_BREAKTHROUGH_TIP_CLOSE = "EVENT_EQUIP_CAN_BREAKTHROUGH_TIP_CLOSE", --装备强化至满级开启突破弹条动画播放结束
    EVENT_EQUIP_DATA_LIST_UPDATE_NOTYFY = "EVENT_EQUIP_DATA_LIST_UPDATE_NOTYFY", --装备数据列表更新
    EVENT_EQUIP_SUIT_PREFAB_DATA_UPDATE_NOTIFY = "EVENT_EQUIP_SUIT_PREFAB_DATA_UPDATE_NOTIFY", --意识组合数据更新

    --基地装备
    EVENT_BASE_EQUIP_DATA_CHANGE_NOTIFY = "EVENT_BASE_EQUIP_DATA_CHANGE_NOTYFY", --穿上基地装备
    EVENT_BASE_EQUIP_DATA_REFRESH = "EVENT_BASE_EQUIP_DATA_REFRESH", --基地装备数据刷新

    -- 好感度偶遇
    EVENT_COMEACROSS_PLAY = "EVENT_COMEACROSS_PLAY", --开始游戏
    EVENT_COMEACROSS_PLAYRESULT = "EVENT_COMEACROSS_PLAYRESULT", --游戏结算


    -- 好感度
    EVENT_FAVORABILITY_MAIN_REFRESH = "EVENT_FAVORABILITY_MAIN_REFRESH", --好感度主界面信息同步
    EVENT_FAVORABILITY_RUMORS_PREVIEW = "EVENT_FAVORABILITY_RUMORS_PREVIEW", --异闻预览
    EVENT_FAVORABILITY_COLLECTGIFT = "EVENT_FAVORABILITY_COLLECTGIFT", --领取礼物
    EVENT_FAVORABILITY_PLOTUNLOCK = "EVENT_FAVORABILITY_PLOTUNLOCK", --剧情解锁
    EVENT_FAVORABILITY_INFOUNLOCK = "EVENT_FAVORABILITY_INFOUNLOCK", --资料解锁
    EVENT_FAVORABILITY_RUMERUNLOCK = "EVENT_FAVORABILITY_RUMERUNLOCK", --异闻解锁
    EVENT_FAVORABILITY_AUDIOUNLOCK = "EVENT_FAVORABILITY_AUDIOUNLOCK", --语音解锁
    EVENT_FAVORABILITY_GIFT = "EVENT_FAVORABILITY_GIFT", --发送礼物
    EVENT_FAVORABILITY_LEVELCHANGED = "EVENT_FAVORABILITY_LEVELCHANGED", --好感度等级经验变化
    EVENT_FAVORABILITY_CHAR_ABILITY_CHANGED = "EVENT_FAVORABILITY_CHAR_ABILITY_CHANGED", --战斗参数变化
    EVENT_FAVORABILITY_CHAR_QUALITY_CHANGED = "EVENT_FAVORABILITY_CHAR_QUALITY_CHANGED", --角色品质变化
    EVENT_FAVORABILITY_ON_GIFT_CHANGED = "EVENT_FAVORABILITY_ON_GIFT_CHANGED", --选中的礼物变化

    -- 新手任务
    EVENT_NEWBIETASK_DAYCHANGED = "EVENT_NEWBIETASK_DAYCHANGED", --新手目标天数变化
    EVENT_NEWBIETASK_PROGRESSCHANGED = "EVENT_NEWBIETASK_PROGRESSCHANGED", --新手进度

    -- 队伍预设
    EVENT_TEAM_PREFAB_CHANGE = "EVENT_TEAM_PREFAB_CHANGE", --队伍预设改变
    EVENT_TEAM_PREFAB_SELECT = "EVENT_TEAM_PREFAB_SELECT", --队伍选中
    EVENT_TEAM_MEMBER_CHANGE = "EVENT_TEAM_MEMBER_CHANGE", --队伍成员发生变化

    -- 公告
    EVENT_NOTICE_PIC_CHANGE = "EVENT_NOTICE_PIC_CHANGE", --宣传图改变
    EVENT_NOTICE_TYPE_CHANAGE = "EVENT_NOTICE_TYPE_CHANAGE", --公告页签改变
    EVENT_NOTICE_CLOSE_TEXT_NOTICE = "EVENT_NOTICE_CLOSE_TEXT_NOTICE", --关闭滚动公告

    -- 活动系统
    EVENT_ACTIVITY_ACTIVITIES_READ_CHAGNE = "EVENT_ACTIVITY_ACTIVITIES_READ_CHAGNE", -- 活动已读状态改变
    EVENT_ACTIVITY_NOTICE_READ_CHAGNE = "EVENT_ACTIVITY_NOTICE_READ_CHAGNE", --公告已读状态改变

    -- 试炼
    EVENT_TRIAL_LEVEL_FINISH = "EVENT_TRIAL_LEVEL_FINISH", --有对应关卡通关



    -- 前传
    EVENT_NOTICE_REFRESHTIME_CHANGE = "EVENT_NOTICE_REFRESHTIME_CHANGE", --刷新时间
    EVENT_NOTICE_CHALLENGESTAGES_CHANGE = "EVENT_NOTICE_CHALLENGESTAGES_CHANGE", --挑战关卡刷新
    EVENT_NOTICE_SELECTCOVER_CHANGE = "EVENT_NOTICE_SELECTCOVER_CHANGE", --
    EVENT_NOTICE_PREQUELDETAIL_CLOSE = "EVENT_NOTICE_PREQUELDETAIL_CLOSE", --详情关闭

    EVENT_NOTICE_TASKINITFINISHED = "EVENT_NOTICE_TASKINITFINISHED",

    -- 弹窗
    EVENT_UIDIALOG_VIEW_ENABLE = "EVENT_UIDIALOG_VIEW_ENABLE", -- 提示弹窗显示

    -- 签到
    EVENT_SING_IN_OPEN_BTN = "EVENT_SING_IN_OPEN_BTN",   -- 签到领取完成开启关闭按钮

    --宿舍
    EVENT_CLICKFURNITURE_GRID = "EVENT_CLICKFURNITURE_GRID",                    -- 点击单个家具
    EVENT_CLICKDRAFT_GRID = "EVENT_CLICKDRAFT_GRID",                            -- 点击单个图纸
    EVENT_CLICKCATEGORY_GRID = "EVENT_CLICKCATEGORY_GRID",                      -- 点击单个家具类型
    EVENT_CLICKFURNITURE_ONROOM = "EVENT_CLICKFURNITURE_ONROOM",                -- 点击场景中的家具
    EVENT_FURNITURE_CREATE_CHANGED = "EVENT_FURNITURE_CREATE_CHANGED",          -- 家具建造可领取

    EVENT_FURNITURE_ONDRAGITEM_CHANGED = "EVENT_FURNITURE_ONDRAGITEM_CHANGED",  -- 家具拖动变化
    EVENT_FURNITURE_REFRESH = "EVENT_FURNITURE_REFRESH",                        -- 刷新家具摆放界面
    EVENT_FURNITURE_CLEANROOM = "EVENT_FURNITURE_CLEANROOM",                    -- 通知全部收起家具
    EVENT_FURNITURE_ON_MODIFY = "EVENT_FURNITURE_ON_MODIFY" ,                   -- 通知家具改变（分解，合成）

    EVENT_CHARACTER_MOOD_CHANGED = "EVENT_CHARACTER_MOOD_CHANGED",              -- 构造体心情值变化
    EVENT_CHARACTER_VITALITY_CHANGED = "EVENT_CHARACTER_VITALITY_CHANGED",      -- 构造体体力情值变化
    EVENT_CHARACTER_ADD_EVENT_NOTIFY = "EVENT_CHARACTER_ADD_EVENT_NOTIFY",      -- 构造体事件通知
    EVENT_CHARACTER_SUB_EVENT_NOTIFY = "EVENT_CHARACTER_SUB_EVENT_NOTIFY",      -- 构造体事件过期通知
    EVENT_CHARACTER_DORMMAIN_EVENT_NOTIFY = "EVENT_CHARACTER_DORMMAIN_EVENT_NOTIFY", -- 通知宿舍主界面有事件



    EVENT_DORM_ROOM = "EVENT_DORM_ROOM",                                        -- 进入宿舍
    EXIT_DORM_ROOM = "EXIT_DORM_ROOM",                                          -- 退出宿舍
    EVENT_DORM_ROOM_ACTIVE_SUCCESS = "EVENT_DORM_ROOM_ACTIVE_SUCCESS",          -- 宿舍激活成功

    EVENT_DORM_CHARACTER_CLICK_SUCCESS = "EVENT_DORM_CHARACTER_CLICK_SUCCESS",             -- 宿舍构造体点击
    EVENT_DORM_CHARACTER_POINTER_UP_SUCCESS = "EVENT_DORM_CHARACTER_POINTER_UP_SUCCESS",   -- 宿舍构造体手指弹起



    EVENT_CHARACTER_SHOW_DIALOBOX = "EVENT_CHARACTER_SHOW_DIALOBOX",            -- 对话气泡显示
    EVENT_CHARACTER_HIDE_DIALOBOX = "EVENT_CHARACTER_HIDE_DIALOBOX",            -- 对话气泡隐藏

    EVENT_CHARACTER_SHOW_3DIOBJ = "EVENT_CHARACTER_SHOW_3DIOBJ",                -- 3DUI显示
    EVENT_CHARACTER_HIDE_3DIOBJ = "EVENT_CHARACTER_HIDE_3DIOBJ",                -- 3DUI隐藏

    EVENT_CHARACTER_CATCH = "EVENT_CHARACTER_CATCH",                            -- 抓起构造体
    EVENT_CHARACTER_EXIT = "EVENT_CHARACTER_EXIT",                              -- 抓起构造体读条放下
    EVENT_CHARACTER_PUT_ON = "EVENT_CHARACTER_PUT_ON",                          -- 构造体抓起读条
    EVENT_CHARACTER_PUT_DOWN = "EVENT_CHARACTER_PUT_DOWN",                      -- 放下构造体

    EVENT_DORM_TOUCH_ENTER = "EVENT_DORM_TOUCH_ENTER",                          -- 宿舍爱抚构造体进入
    EVENT_DORM_TOUCH_SHOW = "EVENT_DORM_TOUCH_SHOW",                            -- 宿舍爱抚构造体显示
    EVENT_DORM_TOUCH_SHOW_VIEW = "EVENT_DORM_TOUCH_SHOW_VIEW",                  -- 宿舍爱抚构造体显示(界面用)
    EVENT_DORM_TOUCH_HIDE = "EVENT_DORM_TOUCH_HIDE",                            -- 宿舍爱抚构造体隐藏

    EVENT_DORM_EXP_DETAIL_SHOW = "EVENT_DORM_EXP_DETAIL_SHOW",                  -- 显示体力详情
    EVENT_DORM_EXP_DETAIL_HIDE = "EVENT_DORM_EXP_DETAIL_HIDE",                  -- 隐藏体力详情

    EVENT_DORM_EXP_SHOW = "EVENT_DORM_EXP_SHOW",                                -- 显示心情条
    EVENT_DORM_EXP_HIDE = "EVENT_DORM_EXP_HIDE",                                -- 隐藏心情条

    EVENT_DORM_HIDE_COMPONET = "EVENT_DORM_HIDE_COMPONET",                      -- 隐藏所有组建
    EVENT_DORM_CLOSE_COMPONET = "EVENT_DORM_CLOSE_COMPONET",                    -- 关闭宿舍3D场景

    EVENT_HOME_CHARACTER_STATUS_CHANGE = "EVENT_HOME_CHARACTER_STATUS_CHANGE",  --宿舍角色状态改变

    EVENT_DORM_SHOW_EVENT_CHANGE = "EVENT_DORM_SHOW_EVENT_CHANGE",              --宿舍角色体力/心情/体力恢复速度/心情恢复速度改变

    EVENT_DORM_FURNITURE_ATTR_TAG = "EVENT_DORM_FURNITURE_ATTR_SHOW",           -- 家具属性显示
    EVENT_DORM_FURNITURE_ATTR_TAG_DETAIL = "EVENT_DORM_FURNITURE_ATTR_TAG_DETAIL",           -- 家具属性显示细节
    EVENT_DORM_FURNITURE_HIDE_ATTR_TAG_DETAIL = "EVENT_DORM_FURNITURE_HIDE_ATTR_TAG_DETAIL",           -- 隐藏家具属性细节
    EVENT_DORM_FURNITURE_HIDE_ALL_ATTR_TAG_DETAIL = "EVENT_DORM_FURNITURE_HIDE_ALL_ATTR_TAG_DETAIL",           -- 隐藏家具属性细节



    --展示厅
    EVENT_CHARACTER_EXHIBITION_REFRESH = "EVENT_CHARACTER_EXHIBITION_REFRESH",  --展示厅奖励信息刷新
    EVENT_CHARACTER_EXHIBITION_AUTOSELECT = "EVENT_CHARACTER_EXHIBITION_AUTOSELECT", --展示厅跳转选中

    --指挥官头像
    EVENT_HEAD_PORTRAIT_NOTIFY = "EVENT_HEAD_PORTRAIT_NOTIFY", --新头像解锁通知
    EVENT_HEAD_PORTRAIT_RESETINFO = "EVENT_HEAD_PORTRAIT_RESETINFO",--新头像解锁通知
    
    --勋章
    EVENT_MEDAL_NOTIFY = "EVENT_MEDAL_NOTIFY", --勋章解锁通知
    EVENT_MEDAL_TIPSOVER = "EVENT_MEDAL_TIPSOVER",--勋章飘窗结束
    EVENT_MEDAL_IN_DETAIL = "EVENT_MEDAL_IN_DETAIL",--进入勋章详情
    -- 教学关卡
    EVENT_PRACTICE_ON_DATA_REFRESH = "EVENT_PRACTICE_ON_DATA_REFRESH",--数据刷新

    -- 单机Boss领取奖励
    EVENT_BOSS_SINGLE_GET_REWARD = "EVENT_BOSS_SINGLE_GET_REWARD", --领取积分奖励

    -- 礼包更新
    EVENT_LB_UPDATE = "EVENT_LB_UPDATE", --礼包

    -- 礼包过期通知
    EVENT_LB_EXPIRE_NOTIFY = "EVENT_LB_EXPIRE_NOTIFY",

    -- 充值
    EVENT_CARD_REFRESH_WELFARE_BTN = "EVENT_CARD_REFRESH_WELFARE_BTN",
    EVENT_DAYLY_REFESH_RECHARGE_BTN = "EVENT_DAYLY_REFESH_RECHARGE_BTN",

    -- 查询角色数据返回
    EVENT_REQUEST_PLAYER_INFO_BACK = "EVENT_REQUEST_PLAYER_INFO_BACK",

    -- 打脸
    EVENT_AUTO_WINDOW_STOP = "EVENT_AUTO_WINDOW_STOP",  -- 打脸暂停

    -- 宿舍打工Reward
    EVENT_DORM_WORK_REDARD= "EVENT_DORM_WORK_REDARD",

    -- 宿舍打工重置
    EVENT_DORM_WORK_RESET= "EVENT_DORM_WORK_RESET",

    -- 宿舍代工
    EVENT_DORM_DAI_GONE_REWARD ="EVENT_DORM_DAI_GONE_REWARD",

    -- 宿舍跳转
    EVENT_DORM_SKIP= "EVENT_DORM_SKIP",
    EVENT_DORM_CLOSE_DETAIL = "EVENT_DORM_CLOSE_DETAIL",

    -- 拍照
    EVENT_PHOTO_ENTER = "EVENT_PHOTO_ENTER", -- 进入拍照状态
    EVENT_PHOTO_LEAVE = "EVENT_PHOTO_LEAVE", -- 离开拍照状态

    -- 爱护
    EVENT_CARESS_SHOW= "EVENT_CARESS_SHOW",

    -- 累计充值更新
    EVENT_ACCUMLATED_UPTATE = "EVENT_ACCUMLATED_UPTATE",

    -- 累计充值奖励领取
    EVENT_ACCUMLATED_REWARD = "EVENT_ACCUMLATED_REWARD",

    -- 宿舍二级界面显示情况
    EVENT_DORM_SECOND_STATE = "EVENT_DORM_SECOND_STATE",
    
    -- 抽奖活动奖池数改变
    EVENT_DRAW_ACTIVITYCOUNT_CHANGE = "EVENT_DRAW_ACTIVITYCOUNT_CHANGE",
    
    -- 抽奖活动奖池变化
    EVENT_DRAW_ACTIVITYDRAW_CHANGE = "EVENT_DRAW_ACTIVITYDRAW_CHANGE",
    
    --试玩区完成情况发生改变
    EVENT_UPDATE_EXPERIMENT = "EVENT_UPDATE_EXPERIMENT",

    -- 节日活动节目刷新
    EVENT_ON_FESTIVAL_CHANGED = "EVENT_ON_FESTIVAL_CHANGED",

    -- 极地活动
    EVENT_BRIEF_CHANGE_TAB = "EVENT_BRIEF_CHANGE_TAB",

    -- 宿舍访问跳转
    EVENT_DORM_VISTOR_SKIP = "EVENT_DORM_VISTOR_SKIP",

    -- 巴别塔刷新
    EVENT_BABEL_STAGE_INFO_ASYNC = "EVENT_BABEL_STAGE_INFO_ASYNC",
    EVENT_BABEL_ACTIVITY_STATUS_CHANGED = "EVENT_BABEL_ACTIVITY_STATUS_CHANGED",
    EVNET_BABEL_CHALLENGE_BUFF_CHANGED = "EVNET_BABEL_CHALLENGE_BUFF_CHANGED",
    --充值失败
    EVNET_FAIL_PAY = "EVNET_FAIL_PAY"
}