---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 0.
--- DateTime: 2019/4/16 11:29
---
XConfigCenter = XConfigCenter or {}

function XConfigCenter.Init()
    local configCenterProfiler = XGame.Profiler:CreateChild("XConfigCenter")
    configCenterProfiler:Start()

    local attribProfiler = configCenterProfiler:CreateChild("XAttribConfig")
    attribProfiler:Start()
    XAttribConfigs.Init()
    attribProfiler:Stop()

    XUiConfigs.Init()

    local guideProfiler = configCenterProfiler:CreateChild("XGuideConfig")
    guideProfiler:Start()
    XGuideConfig.Init()
    guideProfiler:Stop()

    local itemProfiler = configCenterProfiler:CreateChild("XItemConfigs")
    itemProfiler:Start()
    XItemConfigs.Init()
    itemProfiler:Stop()

    local characterProfiler = configCenterProfiler:CreateChild("XCharacterConfigs")
    characterProfiler:Start()
    XCharacterConfigs.Init()
    characterProfiler:Stop()

    local signBoardProfiler = configCenterProfiler:CreateChild("XSignBoardConfigs")
    signBoardProfiler:Start()
    XSignBoardConfigs.Init()
    signBoardProfiler:Stop()

    local equipProfiler = configCenterProfiler:CreateChild("XEquipConfig")
    equipProfiler:Start()
    XEquipConfig.Init()
    equipProfiler:Stop()

    local comeAcrossProfiler = configCenterProfiler:CreateChild("XComeAcrossConfig")
    comeAcrossProfiler:Start()
    XComeAcrossConfig.Init()
    comeAcrossProfiler:Stop()

    local favorabilityProfiler = configCenterProfiler:CreateChild("XFavorabilityConfigs")
    favorabilityProfiler:Start()
    XFavorabilityConfigs.Init()
    favorabilityProfiler:Stop()

    local arenaProfiler = configCenterProfiler:CreateChild("XArenaConfigs")
    arenaProfiler:Start()
    XArenaConfigs.Init()
    arenaProfiler:Stop()

    local trialProfiler = configCenterProfiler:CreateChild("XTrialConfigs")
    trialProfiler:Start()
    XTrialConfigs.Init()
    trialProfiler:Stop()

    local communicationProfiler = configCenterProfiler:CreateChild("XCommunicationConfig")
    communicationProfiler:Start()
    XCommunicationConfig.Init()
    communicationProfiler:Stop()

    local prequelProfiler = configCenterProfiler:CreateChild("XPrequelConfigs")
    prequelProfiler:Start()
    XPrequelConfigs.Init()
    prequelProfiler:Stop()

    local taskProfiler = configCenterProfiler:CreateChild("XTaskConfig")
    taskProfiler:Start()
    XTaskConfig.Init()
    taskProfiler:Stop()

    local fubenProfiler = configCenterProfiler:CreateChild("XFubenConfigs")
    fubenProfiler:Start()
    XFubenConfigs.Init()
    fubenProfiler:Stop()

    local taskForceProfiler = configCenterProfiler:CreateChild("XTaskForceConfigs")
    taskForceProfiler:Start()
    XTaskForceConfigs.Init()
    taskForceProfiler:Stop()

    local drawProfiler = configCenterProfiler:CreateChild("XDrawConfigs")
    drawProfiler:Start()
    XDrawConfigs.Init()
    drawProfiler:Stop()

    local gachaProfiler = configCenterProfiler:CreateChild("XGachaConfigs")
    gachaProfiler:Start()
    XGachaConfigs.Init()
    gachaProfiler:Stop()
    
    local fubenMailLineProfiler = configCenterProfiler:CreateChild("XFubenMainLineConfigs")
    fubenMailLineProfiler:Start()
    XFubenMainLineConfigs.Init()
    fubenMailLineProfiler:Stop()

    local fubenBossSingleProfiler = configCenterProfiler:CreateChild("XFubenBossSingleConfigs")
    fubenBossSingleProfiler:Start()
    XFubenBossSingleConfigs.Init()
    fubenBossSingleProfiler:Stop()

    local fubenExperimentProfiler = configCenterProfiler:CreateChild("XFubenExperimentConfigs")
    fubenExperimentProfiler:Start()
    XFubenExperimentConfigs.Init()
    fubenExperimentProfiler:Stop()

    local mailProfiler = configCenterProfiler:CreateChild("XMailConfigs")
    mailProfiler:Start()
    XMailConfigs.Init()
    mailProfiler:Stop()

    local bfrtProfiler = configCenterProfiler:CreateChild("XBfrtConfigs")
    bfrtProfiler:Start()
    XBfrtConfigs.Init()
    bfrtProfiler:Stop()

    local bountyTaskProfiler = configCenterProfiler:CreateChild("XBountyTaskConfigs")
    bountyTaskProfiler:Start()
    XBountyTaskConfigs.Init()
    bountyTaskProfiler:Stop()

    local hostelProfiler = configCenterProfiler:CreateChild("XHostelConfigs")
    hostelProfiler:Start()
    XHostelConfigs.Init()
    hostelProfiler:Stop()

    local baseEquipProfiler = configCenterProfiler:CreateChild("XBaseEquipConfigs")
    baseEquipProfiler:Start()
    XBaseEquipConfigs.Init()
    baseEquipProfiler:Stop()

    local furnitureProfiler = configCenterProfiler:CreateChild("XFurnitureConfigs")
    furnitureProfiler:Start()
    XFurnitureConfigs.Init()
    furnitureProfiler:Stop()

    XPayConfigs.Init()

    local fubenExploreProfiler = configCenterProfiler:CreateChild("XFubenExploreConfigs")
    fubenExploreProfiler:Start()
    XFubenExploreConfigs.Init()
    fubenExploreProfiler:Stop()

    local fubenActivityBranchProfiler = configCenterProfiler:CreateChild("XFubenActivityBranchConfigs")
    fubenActivityBranchProfiler:Start()
    XFubenActivityBranchConfigs.Init()
    fubenActivityBranchProfiler:Stop()

    XFubenActivityBossSingleConfigs.Init()

    XDormConfig.Init()

    local ExhibitionProfiler = configCenterProfiler:CreateChild("XExhibitionConfigs")
    ExhibitionProfiler:Start()
    XExhibitionConfigs.Init()
    ExhibitionProfiler:Stop()

    local AutoWindowProfiler = configCenterProfiler:CreateChild("XAutoWindowConfigs")
    AutoWindowProfiler:Start()
    XAutoWindowConfigs.Init()
    AutoWindowProfiler:Stop()

    local playerInfoConfigs = configCenterProfiler:CreateChild("XPlayerInfoConfigs")
    playerInfoConfigs:Start()
    XPlayerInfoConfigs.Init()
    playerInfoConfigs:Stop()

    local SignInProfiler = configCenterProfiler:CreateChild("XSignInConfigs")
    SignInProfiler:Start()
    XSignInConfigs.Init()
    SignInProfiler:Stop()

    local ReportConfigs = configCenterProfiler:CreateChild("XReportConfigs")
    ReportConfigs:Start()
    XReportConfigs.Init()
    ReportConfigs:Stop()


    local practiceConfigs = configCenterProfiler:CreateChild("XPracticeConfigs")
    practiceConfigs:Start()
    XPracticeConfigs.Init()
    practiceConfigs:Stop()

    local shopConfigs = configCenterProfiler:CreateChild("XShopConfig")
    shopConfigs:Start()
    XShopConfigs.Init()
    shopConfigs:Stop()

    local helpCourseConfig = configCenterProfiler:CreateChild("XHelpCourseConfig")
    helpCourseConfig:Start()
    XHelpCourseConfig.Init()
    helpCourseConfig:Stop()
    
    local MedalConfigs = configCenterProfiler:CreateChild("XMedalConfigs")
    MedalConfigs:Start()
    XMedalConfigs.Init()
    MedalConfigs:Stop()

    local guildProfiler = configCenterProfiler:CreateChild("XGuildConfig")
    guildProfiler:Start()
    XGuildConfig.Init()
    guildProfiler:Stop()

    local festivalProfiler = configCenterProfiler:CreateChild("XFestivalActivityConfig")
    festivalProfiler:Start()
    XFestivalActivityConfig.Init()
    festivalProfiler:Stop()

    local babelTowerProfiler = configCenterProfiler:CreateChild("XFubenBabelTowerConfigs")
    babelTowerProfiler:Start()
    XFubenBabelTowerConfigs.Init()
    babelTowerProfiler:Stop()

    XActivityConfigs.Init()
    XPurchaseConfigs.Init()
    XActivityBriefConfigs.Init()
    XSetConfigs.Init()
    XRedEnvelopeConfigs.Init()

    configCenterProfiler:Stop()
end